name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    # - cron: "* */12 * * *"
    # Runs every week at 12am UTF on Sunday
    - cron: "0 0 * * 0"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: false
